version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  web:
    image: drupal:8.7.3-fpm-alpine
    depends_on:
      - db
    ports:
      - "80:80"
